### ISSUE TITLE
Related works

### ISSUE THREAD

**Issue by isamert** [HarambeSoft/plus-one#3]
Benzer anket uygulamaları ile ilgili görsel materyallere ihtiyacımız var.

**Comment by YucelT94** [comment]
UI kısmını sonraya bıraksak ilk başlarken sadece bi kaç buton işimizi görmez mi?

**Comment by isamert** [comment]
Hem UI için, hem de programın içeriği için gerekli. Yani en azından bir şeyler toplamak, neler yapacağımız hakkında bize de fikir verir.

**Comment by YucelT94** [comment]
Biraz bakındım ama survey uygulamalarının UI kısımları leş genelde içerik için olabilir

**Comment by gizemfitoz** [comment]
Bence pazartesi çıkışta biraz arayüz tasarlayalım. Sayfalarda tablara neler koyacağız onları düşünelim, onlara göre materyal bulmak daha kolay olur
