### ISSUE TITLE
Arayüz tasarımları

### ISSUE THREAD

**Issue by isamert** [HarambeSoft/plus-one#6]
Taslak düzeyinde bir şeylere ihtiyacımız var. Tasarlanacak sayfalar şöyle:
- [x] Login screen
- `Sign in with Google` simgesi olmalı. Aynı zamanda kullanıcı mail + şifre kombinasyonu ile giriş yapacak.
- [x] Sign up screen
- Yine `Sign in with Google` simgesi olmalı burada. Şimdilik `user name`, `password`, `mail` alanları yeterli.
- [x] Profile view
-  Hem o anki kullanıcı hem de başka kulanıcıların bilgilerini gösterebilecek şekilde olması lazım. Örneğin giriş yapmış kullanıcı kendi bilgilerini görüntülerken `edit` simgeleri de görecek fakat başka insanların profilinde bu simgler çıkmayacak. Obje isimlendirmeleri önemli. Bu sayfada olacak şeyler şunlar:
  - Profil resmi
  - Kullanıcı adı
  - Şifre *
  - E-mail *
  - Şehir *
  - Meslek *
  - Son cevaplanan anketler

Şimdilik öncelikli ihtiyaçlar bunlar, API hazır olduğunda hızlıca birleştiririz.
*: Diğer kullanıcılara gözükmeyecek.
- [x] Poll view
- [x] Poll create view
- [x] Category view

Buradakilere bir şey yapmadım, database'yi tam bitirdikten sonra buralarda neler olması gerektiğini yazacağım. Daha eklenecek birkaç sayfa var. Aynı zamanda bunların tab içinde mi, yoksa ayrı bir sayfa olarak mı tutulacağına karar verilmeli.

**Comment by sbozturk** [comment]
Login screen checked

**Comment by sbozturk** [comment]
Completed
